name: Check Parameter Definitions on change PR

on:
  # push:
  #   branches:
  #     - main

  # Update in response to changes on input files or validation action
  pull_request:
    paths: 
      - 'parameters.json' # Parameters
      - 'parameters_schema.json' # Schema
      - '.github/actions/validate_params/**' # Validation tools
      - '.github/workflow/verify_params/**' # This workflow
  push:
    paths: 
      # - '**'
      - 'parameters.json' # Parameters
      - 'parameters_schema.json' # Schema
      - '.github/actions/validate_params/**' # Validation tools
      - '.github/workflow/verify_params/**' # This workflow

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/actions/validate_params/requirements.txt

      - name: JSON validation on proposed pull requests
        if: github.event_name == 'pull_request'
        run: python .github/actions/validate_params/validate_params.py --file parameters.json --schema parameters_schema.json

      - name: JSON validation and update autogenerated files on push
        if: github.event_name == 'push'
        run: |
          python .github/actions/validate_params/validate_params.py --file parameters.json --schema parameters_schema.json --proto parameters.proto --csv_file parameters.csv
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add parameters.proto
          git add parameters.csv
          git diff --cached --quiet || git commit -m "Automatic update protobuf and CSV files from validated JSON"
          git push